### ISSUE TITLE
Blank black screen

### ISSUE THREAD

**Issue by khalidchawtany** [onivim/oni#1235]
I am on OS X 10.13.2, running latest head Neovim, and build Oni from master. When I launch Oni I get a blank black screen.

**Comment by Dcryfm** [comment]
@khalidchawtany I have encountered a similar situation, which should be the effect of existing vimrc or init.vim.

**Comment by bryphe** [comment]
Hi @khalidchawtany ,

Yes, knowing if you've customized `config.js` or are using a default `init.vim` would be helpful.

In addition, can you try running `oni --debug` and sharing the output of the browser console? I'm curious if there is some error on load.

If you've built from master before, you may want to clear out your `node_modules` folder, re-run `yarn install`, and re-run `npm run build`.

**Comment by khalidchawtany** [comment]
I have no error on launching nvim from terminal or launching nvim-qt. Indeed I have editted the config.js yet I cannot find where it is located to delete it :)
I did delete node_modules and did reinstall and rebuild. However, I still get the same result.

running `oni --debug` I get the following eror:
```
/Users/juju/Development/Applications/oni/lib/browser/bundle.js:1 Uncaught Error: Module build failed: Error: Typescript emitted no output for /Users/juju/Development/Applications/oni/browser/src/index.tsx.
    at successLoader (/Users/juju/Development/Applications/oni/node_modules/ts-loader/dist/index.js:39:15)
    at Object.loader (/Users/juju/Development/Applications/oni/node_modules/ts-loader/dist/index.js:21:12)
    at successLoader (/Users/juju/Development/Applications/oni/node_modules/ts-loader/dist/index.js:39:15)
    at Object.loader (/Users/juju/Development/Applications/oni/node_modules/ts-loader/dist/index.js:21:12)
    at Object.<anonymous> (file:///Users/juju/Development/Applications/oni/lib/browser/bundle.js:1:537)
    at b (file:///Users/juju/Development/Applications/oni/lib/browser/bundle.js:1:101)
    at Object.<anonymous> (file:///Users/juju/Development/Applications/oni/lib/browser/bundle.js:1:512)
    at b (file:///Users/juju/Development/Applications/oni/lib/browser/bundle.js:1:101)
    at file:///Users/juju/Development/Applications/oni/lib/browser/bundle.js:1:473
    at file:///Users/juju/Development/Applications/oni/lib/browser/bundle.js:1:483

```

**Comment by khalidchawtany** [comment]
I just rebuilt again and it works now.

**Comment by bryphe** [comment]
Thanks for the update, glad its working now!

**Comment by khalidchawtany** [comment]
Hi @bryphe,
I have build oni from current master and I cannot get it to work.
- I have tried deleting the *node_modules* dir.
- I have build using `npm run build`
- I have build using `nom run build-debug`
- I have ran it using the *oni.application*
- I have ran it using terminal *oni* and *oni --debug* commands


```
0.bundle.js Failed to load resource: net::ERR_CONNECTION_REFUSED
/Users/juju/Development/Applications/oni/lib/browser/bundle.js:99 Uncaught (in promise) Error: Loading chunk 0 failed.
    at HTMLScriptElement.onScriptComplete (/Users/juju/Development/Applications/oni/lib/browser/bundle.js:99)

```

**Comment by khalidchawtany** [comment]
A gain after many many many .......  tries it is working again.

I noticed that there was an error about *missing ocaml* while building.
I installed ocaml using brew. After rebuilding and running *oni* I got a different error which showed that I had a wrong config entry `  "environment.additionalPaths" : "usr/local/bin",` it should be `"environment.additionalPaths" : "/usr/local/bin"`.

**Comment by bryphe** [comment]
Thanks for all the details, @khalidchawtany ! I'm glad you finally got it working. Sorry for all the trouble.

**Comment by bryphe** [comment]
By chance - did you have `NODE_ENV` set to `development` ever? I'm curious if that could be related here.

**Comment by khalidchawtany** [comment]
I cheked that too as it was causing a similar issue on Ubuntu I think. However, in my case no env var was set.

**Comment by tarciozemel** [comment]
Just found Oni and install it for some tests. I opened some files and start to play with some configs. At this point, I got this black screen after a restart.

I already tried to reinstall many times without success.

I'm in Linux ubuntu-pc 4.13.0-37-generic # 42~16.04.1-Ubuntu.

Here's the log error:

```
bundle.js:1 $env:ONI_CONFIG_FILE: undefined
bundle.js:1 [Configuration] Adding file: /home/tarciozemel/.oni/config.js
/home/tarciozemel/.oni/config.js:16 config deactivated
/home/tarciozemel/.oni/config.js:16 config deactivated
bundle.js:1 Oni.Start.Config: 100.651123046875ms
bundle.js:1 [Configuration] Got update.
/home/tarciozemel/.oni/config.js:16 config deactivated
/home/tarciozemel/.oni/config.js:16 config deactivated
bundle.js:1 $env:ONI_CONFIG_FILE: undefined
bundle.js:1 Oni.Start.Plugins.Discover: 4.290283203125ms
bundle.js:1 Oni.Start.Themes: 78.55615234375ms
bundle.js:1 [Notifications] Setting enabled: true
bundle.js:1 [OniEditor::enter]
bundle.js:1 [NeovimEditor::enter]
bundle.js:1 [OniEditor::init] Called with filesToOpen: 
bundle.js:1 [NeovimEditor::init] Called with filesToOpen: 
bundle.js:1 [NeovimProcessSpawner::startNeovim] Neovim process path: nvim
bundle.js:1 [NeovimProcessSpawner::startNeovim] Starting Neovim - process: 19586
bundle.js:1 Initializing neovim process using transport: stdio
bundle.js:1 NeovimInstance: Neovim started
bundle.js:1 [NeovimInstance::_checkAndFixIfBlocked] checking mode...
bundle.js:1 [NeovimInstance::_checkAndFixIfBlocked] Not blocking mode.
bundle.js:1 [NeovimInstance::_attachUI] Neovim version reported as 0.2.2
bundle.js:1 [NeovimInstance::_attachUI] Using startup options: {"rgb":true,"popupmenu_external":true,"ext_tabline":true,"ext_cmdline":true,"ext_wildmenu":true} and size: 124, NaN
bundle.js:1 Attach success
bundle.js:1 NeovimInstance.Start.Attach: 20.706787109375ms
bundle.js:1 NeovimInstance.Start: 1462.075927734375ms
bundle.js:1 [NeovimEditor] Colors changed: onedark - background: #000000 foreground: #000000
bundle.js:1 [SharedNeovimInstance::start] Starting...
bundle.js:1 [NeovimProcessSpawner::startNeovim] Neovim process path: nvim
bundle.js:1 [NeovimProcessSpawner::startNeovim] Starting Neovim - process: 19587
bundle.js:1 Initializing neovim process using transport: stdio
bundle.js:1 NeovimInstance: Neovim started
bundle.js:1 [NeovimInstance::_checkAndFixIfBlocked] checking mode...
bundle.js:1 [NeovimTokenColorSynchronizer::synchronizeTokenColors] Setting 11 highlights
bundle.js:1 [NeovimTokenColorSynchronizer::synchronizeTokenColors] Highlights set successfully
bundle.js:1 [NeovimInstance::_checkAndFixIfBlocked] Not blocking mode.
bundle.js:1 [NeovimInstance::_attachUI] Neovim version reported as 0.2.2
bundle.js:1 [NeovimInstance::_attachUI] Using startup options: {"rgb":true,"popupmenu_external":true,"ext_tabline":true,"ext_cmdline":true,"ext_wildmenu":true} and size: NaN, NaN
bundle.js:1 Attach success
bundle.js:1 NeovimInstance.Start.Attach: 9.382080078125ms
bundle.js:1 NeovimInstance.Start: 55.23388671875ms
bundle.js:1 [SharedNeovimInstance::start] Started successfully!
bundle.js:1 Oni.Start.Editors: 1605.610107421875ms
bundle.js:1 Oni.Start.Sidebar: 55.73291015625ms
bundle.js:1 [PLUGIN] Activating: oni-plugin-statusbar
bundle.js:1 [PLUGIN] Activation successful.
bundle.js:1 [PLUGIN] Activating: oni-plugin-buffers
bundle.js:1 [PLUGIN] Activation successful.
bundle.js:1 [PLUGIN] Activating: oni-plugin-git
bundle.js:1 [PLUGIN] Activation successful.
bundle.js:1 [PLUGIN] Activating: oni-plugin-typescript
bundle.js:1 [PLUGIN] Activation successful.
bundle.js:1 [PLUGIN] Activating: oni-plugin-markdown-preview
bundle.js:1 [PLUGIN] Activation successful.
/home/tarciozemel/.oni/config.js:4 config activated
bundle.js:1 $env:ONI_CONFIG_FILE: undefined
bundle.js:1 UserSnippetProvider - installing watcher...
bundle.js:1 $env:ONI_CONFIG_FILE: undefined
bundle.js:1 [Language Manager - Config] Registering info for language: html - command: /opt/Oni/resources/app/node_modules/vscode-html-languageserver-bin/htmlServerMain.js
bundle.js:1 [Language Manager - Config] Registering info for language: go - command: go-langserver
bundle.js:1 [Language Manager - Config] Registering info for language: python - command: pyls
bundle.js:1 [Language Manager - Config] Registering info for language: cpp - command: clangd
bundle.js:1 [Language Manager - Config] Registering info for language: c - command: clangd
bundle.js:1 [Language Manager - Config] Registering info for language: css - command: /opt/Oni/resources/app/node_modules/vscode-css-languageserver-bin/cssServerMain.js
bundle.js:1 [Language Manager - Config] Registering info for language: less - command: /opt/Oni/resources/app/node_modules/vscode-css-languageserver-bin/cssServerMain.js
bundle.js:1 [Language Manager - Config] Registering info for language: scss - command: /opt/Oni/resources/app/node_modules/vscode-css-languageserver-bin/cssServerMain.js
bundle.js:1 [Language Manager - Config] Registering info for language: reason - command: /opt/Oni/resources/app/node_modules/ocaml-language-server/bin/server/index.js
bundle.js:1 [Language Manager - Config] Registering info for language: ocaml - command: /opt/Oni/resources/app/node_modules/ocaml-language-server/bin/server/index.js
bundle.js:1 TypeError: path must be a string or Buffer
    at fs.stat (fs.js:936)
    at fs.stat (ELECTRON_ASAR.js:290)
    at internal/util.js:227
    at O.<anonymous> (0.bundle.js:537)
    at Generator.next (<anonymous>)
    at 0.bundle.js:537
    at Promise (<anonymous>)
    at I (0.bundle.js:537)
    at O.pathIsDir (0.bundle.js:537)
    at updateBranchIndicator (/opt/Oni/resources/app/vim/core/oni-plugin-git/index.js:21)
/opt/Oni/resources/app/vim/core/oni-plugin-git/index.js:77 [Oni.plugin.git]:  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28)
    at Object.dirname (path.js:1345)
    at updateBranchIndicator (/opt/Oni/resources/app/vim/core/oni-plugin-git/index.js:22)
    at <anonymous>
bundle.js:1 Oni.Start.Activate: 250.281005859375ms
bundle.js:1 Oni.Start: 2508.712158203125ms
bundle.js:1 TypeError: path must be a string or Buffer
    at fs.stat (fs.js:936)
    at fs.stat (ELECTRON_ASAR.js:290)
    at internal/util.js:227
    at O.<anonymous> (0.bundle.js:537)
    at Generator.next (<anonymous>)
    at 0.bundle.js:537
    at Promise (<anonymous>)
    at I (0.bundle.js:537)
    at O.pathIsDir (0.bundle.js:537)
    at updateBranchIndicator (/opt/Oni/resources/app/vim/core/oni-plugin-git/index.js:21)
/opt/Oni/resources/app/vim/core/oni-plugin-git/index.js:77 [Oni.plugin.git]:  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28)
    at Object.dirname (path.js:1345)
    at updateBranchIndicator (/opt/Oni/resources/app/vim/core/oni-plugin-git/index.js:22)
    at <anonymous>
bundle.js:1 TypeError: path must be a string or Buffer
    at fs.stat (fs.js:936)
    at fs.stat (ELECTRON_ASAR.js:290)
    at internal/util.js:227
    at O.<anonymous> (0.bundle.js:537)
    at Generator.next (<anonymous>)
    at 0.bundle.js:537
    at Promise (<anonymous>)
    at I (0.bundle.js:537)
    at O.pathIsDir (0.bundle.js:537)
    at updateBranchIndicator (/opt/Oni/resources/app/vim/core/oni-plugin-git/index.js:21)
/opt/Oni/resources/app/vim/core/oni-plugin-git/index.js:77 [Oni.plugin.git]:  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28)
    at Object.dirname (path.js:1345)
    at updateBranchIndicator (/opt/Oni/resources/app/vim/core/oni-plugin-git/index.js:22)
    at <anonymous>
bundle.js:1 TypeError: path must be a string or Buffer
    at fs.stat (fs.js:936)
    at fs.stat (ELECTRON_ASAR.js:290)
    at internal/util.js:227
    at O.<anonymous> (0.bundle.js:537)
    at Generator.next (<anonymous>)
    at 0.bundle.js:537
    at Promise (<anonymous>)
    at I (0.bundle.js:537)
    at O.pathIsDir (0.bundle.js:537)
    at updateBranchIndicator (/opt/Oni/resources/app/vim/core/oni-plugin-git/index.js:21)
/opt/Oni/resources/app/vim/core/oni-plugin-git/index.js:77 [Oni.plugin.git]:  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28)
    at Object.dirname (path.js:1345)
    at updateBranchIndicator (/opt/Oni/resources/app/vim/core/oni-plugin-git/index.js:22)
    at <anonymous>

**Comment by tarciozemel** [comment]
@badosu Noup. I can use Oni now! :ice_cream:
