### ISSUE TITLE
yarn install results in error

### ISSUE THREAD

**Issue by GoAwayPeter** [onivim/oni#1440]
After running the specified 'First build' instructions in the dev wiki.

```
[master !]George@localhost oni$ yarn install
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning vscode-languageclient@3.5.0: The engine "vscode" appears to be invalid.
info 7zip-bin-linux@1.1.0: The platform "darwin" is incompatible with this module.
info "7zip-bin-linux@1.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-win@2.1.1: The platform "darwin" is incompatible with this module.
info "7zip-bin-win@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
warning " > oni-api@0.0.26" has unmet peer dependency "vscode-languageserver-types@^3.5.0".
warning " > oni-api@0.0.26" has unmet peer dependency "rimraf@^2.6.2".
warning " > react-electron-web-view@2.0.1" has incorrect peer dependency "react@^15.0.0".
warning " > react-electron-web-view@2.0.1" has incorrect peer dependency "react-dom@^15.0.0".
warning "jsdom > request-promise-native@1.0.5" has unmet peer dependency "request@^2.34".
warning "jsdom > request-promise-native > request-promise-core@1.1.1" has unmet peer dependency "request@^2.34".
[4/4] 📃  Building fresh packages...
[1/11] ⡀ keyboard-layout
[2/11] ⡀ oni-neovim-binaries
[3/11] ⡀ oni-ripgrep
[4/11] ⡀ oniguruma
error /Users/George/Documents/oni/node_modules/oni-ripgrep: Command failed.
Exit code: 1
Command: node lib/postinstall.js
Arguments:
Directory: /Users/George/Documents/oni/node_modules/oni-ripgrep
Output:
/Users/George/Documents/oni/node_modules/oni-release-downloader/lib/index.js:15
const downloadGithubRelease = async (baseDir, downloadMetadata) => {
                                    ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```

**Comment by GoAwayPeter** [comment]
Had an old version of node...
