### ISSUE TITLE
Crash report after creating an empty tab

### ISSUE THREAD

**Issue by hoschi** [onivim/oni#1588]
![2018-02-20-174815_1403x1339_scrot](https://user-images.githubusercontent.com/163128/36437080-550a644e-1666-11e8-9094-cc0d6729cbce.png)

**Comment by hoschi** [comment]
@bryphe to tone down the settings for uglifyJS to get better stack traces? This one is by far the most human readable which I saw in the last couple of days (see other tickets). I didn't checked the webpack config nor tested the file size impact, but "put all in one file" and "variable rewriting" seems to be overkill for a desktop app?

**Comment by hoschi** [comment]
Happens also without my own init.vim. Sometimes also after opening a file, but with a 2s delay.

**Comment by bryphe** [comment]
> @bryphe Did you thought about toning down the settings for uglifyJS to get better stack traces? This one is by far the most human readable which I saw in the last couple of days (see other tickets)

Ah ya, I was considering it actually. The one thing I'd like to do is switch to the asar bundle - #350 - which puts all the source files in one place (essentially does what webpack does...). Otherwise there is impact on the startup perf for production builds.

**Comment by hoschi** [comment]
And is it possible to have unminified code in a asar bundle, for better readability?

**Comment by hoschi** [comment]
@CrossR I still getting this one with your fix for #1579 where I didn't see the bug from #1579 happened yet :crossed_fingers:

**Comment by CrossR** [comment]
Hmm, I'll have a further look into this tonight. Have you got a repro for this one as well?

**Comment by hoschi** [comment]
Unfortunately not, this one is not as often as the other was. But here is an updated stack trace:
```
Uncaught (in promise) Error: Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at IOSession.Session.change (/home/hoschi/repos/oni-master/node_modules/typescript/lib/tsserver.js:90017:26)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/home/hoschi/repos/oni-master/node_modules/typescript/lib/tsserver.js:89065:31)
    at /home/hoschi/repos/oni-master/node_modules/typescript/lib/tsserver.js:90393:88
    at IOSession.Session.executeWithRequestId (/home/hoschi/repos/oni-master/node_modules/typescript/lib/tsserver.js:90384:28)
    at IOSession.Session.executeCommand (/home/hoschi/repos/oni-master/node_modules/typescript/lib/tsserver.js:90393:33)
    at IOSession.Session.onMessage (/home/hoschi/repos/oni-master/node_modules/typescript/lib/tsserver.js:90413:35)
    at Interface.<anonymous> (/home/hoschi/repos/oni-master/node_modules/typescript/lib/tsserver.js:91614:27)
    at emitOne (events.js:115:13)
    at Interface.emit (events.js:210:7)
    at Interface._onLine (readline.js:278:10)
    at Interface._normalWrite (readline.js:420:12)
    at Socket.ondata (readline.js:138:10)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)
    at IOSession.Session.change (/home/hoschi/repos/oni-master/node_modules/typescript/lib/tsserver.js:90017:26)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/home/hoschi/repos/oni-master/node_modules/typescript/lib/tsserver.js:89065:31)
    at /home/hoschi/repos/oni-master/node_modules/typescript/lib/tsserver.js:90393:88
    at IOSession.Session.executeWithRequestId (/home/hoschi/repos/oni-master/node_modules/typescript/lib/tsserver.js:90384:28)
    at IOSession.Session.executeCommand (/home/hoschi/repos/oni-master/node_modules/typescript/lib/tsserver.js:90393:33)
    at IOSession.Session.onMessage (/home/hoschi/repos/oni-master/node_modules/typescript/lib/tsserver.js:90413:35)
    at Interface.<anonymous> (/home/hoschi/repos/oni-master/node_modules/typescript/lib/tsserver.js:91614:27)
    at emitOne (events.js:115:13)
    at Interface.emit (events.js:210:7)
    at Interface._onLine (readline.js:278:10)
    at Interface._normalWrite (readline.js:420:12)
    at Socket.ondata (readline.js:138:10)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)
    at TypeScriptServerHost._parseResponse (/home/hoschi/repos/oni-master/vim/core/oni-plugin-typescript/lib/TypeScriptServerHost.js:322:49)
    at Interface.<anonymous> (/home/hoschi/repos/oni-master/vim/core/oni-plugin-typescript/lib/TypeScriptServerHost.js:116:39)
    at emitOne (events.js:115:13)
    at Interface.emit (events.js:210:7)
    at Interface._onLine (readline.js:278:10)
    at Interface._normalWrite (readline.js:420:12)
    at Socket.ondata (readline.js:138:10)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
```

**Comment by hoschi** [comment]
Ah and it also happens when cloning a tab with `:tab split` not only on empty tabs, I believe.

**Comment by hoschi** [comment]
@CrossR finally found a repro
* Get files from this gist and put it in a dir https://gist.github.com/hoschi/d03e24220f866e5a7b9a6a66d393187c
* open oni
* use `ctrl+p` to open `Volume.js`
* wait a second for language server
* use `ctrl+p` to open `applyTemplate.js`
* now you should get the red error notification

**Comment by CrossR** [comment]
Managed to repro it now. On my Windows machine using a built artifact from AppVeyor (ie a minified etc file) I get the same error as you.

On my dev machine I get:

![image](https://user-images.githubusercontent.com/10038688/36607138-a8382ce2-18bd-11e8-93d0-9ce74b07559a.png)

Which is significantly less scary looking.
I can only assume they are the same issue since I follow the same pattern to get them to happen, but its obviously a bit awkward with the minifed code.

To get this to happen on Windows at least, I have to wait until the "spinner" next to the mouse goes away after opening the first file, and then the opening of the next file causes the error.

So really I'm a bit confused...the error I see in my dev env is the notification view erroring....which doesn't really help since I don't know what notification it was attempting to show then errored on. Its also possible this is just a different error, but its confusing either way.

I'll keep having a look.

**Comment by CrossR** [comment]
I've came back to this today, and it doesn't seem to be an issue for me, at least the test I was doing last time that consistently made it happen doesn't work anymore.

Its possible its been fixed in the time since I last checked since there is pretty rapid development happening!

**Comment by hoschi** [comment]
I'll try then latest master and report back.

**Comment by CrossR** [comment]
I'm unable to causes this any more whereas I was able to consistently previously.

I'll close this out for now, and if it re-appears we can re-open.

**Comment by feltech** [comment]
I get this consistently when running the `Neovim.CallOniCommands` CI test and the latest master.  The test assertions seem to pass, but the test fails with the final log line
```
[SEVERE] file:///mnt/2TB-Storage/Working/Programs/oni/lib/browser/bundle.js 0:2122 "Received notification for - Unhandled Rejection:Error: Error processing request. Debug Failure. False expression.\nError: Debug Failure. False expression.\n    at IOSession.Session.change (/mnt/2TB-Storage/Working/Programs/oni/node_modules/typescript/lib/tsserver.js:91678:26)\n    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/mnt/2TB-Storage/Working/Programs/oni/node_modules/typescript/lib/tsserver.js:90696:31)\n    at /mnt/2TB-Storage/Working/Programs/oni/node_modules/typescript/lib/tsserver.js:92067:88\n    at IOSession.Session.executeWithRequestId (/mnt/2TB-Storage/Working/Programs/oni/node_modules/typescript/lib/tsserver.js:92058:28)\n    at IOSession.Session.executeCommand (/mnt/2TB-Storage/Working/Programs/oni/node_modules/typescript/lib/tsserver.js:92067:33)\n    at IOSession.Session.onMessage (/mnt/2TB-Storage/Working/Programs/oni/node_modules/typescript/lib/tsserver.js:92087:35)\n    at Interface.\u003Canonymous> (/mnt/2TB-Storage/Working/Programs/oni/node_modules/typescript/lib/tsserver.js:93288:27)\n    at emitOne (events.js:116:13)\n    at Interface.emit (events.js:211:7)\n    at Interface._onLine (readline.js:282:10)\n    at Interface._normalWrite (readline.js:424:12)\n    at Socket.ondata (readline.js:141:10)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at Pipe.onread (net.js:594:20)\nPlease report this error."
```

**Comment by feltech** [comment]
Theia looks interesting.  Are you planning to move the entire UI to Theia, or just extract the language server?  Is there a ticket for this?  I couldn't find one.

**Comment by Akin909** [comment]
[Theia](https://github.com/theia-ide/typescript-language-server) is just an lsp  client (or rather the project I'm referring to is) Oni handles all of its ui it doesn't provide any ui. We've so far discussed it as part of #1593 and in #1717
