### ISSUE TITLE
Error building Oni on OSX

### ISSUE THREAD

**Issue by parkerault** [onivim/oni#1920]
Using:
  - OSX 10.12.6 (16G1212)
  - npm 5.6.0
  - yarn 1.5.1
  - node 9.4.0
  - nvm 0.33.8

I get the following warning when running `npm run build`:

```
WARNING in ./node_modules/cross-spawn/index.js
Module not found: Error: Can't resolve 'spawn-sync' in '/Users/enolammt/Documents/projects/oni/node_modules/cross-spawn'
 @ ./node_modules/cross-spawn/index.js 32:26-47
 @ ./node_modules/execa/index.js
 @ ./node_modules/shell-env/index.js
 @ ./browser/src/Plugins/Api/Process.ts
 @ ./browser/src/Plugins/PluginInstaller.ts
 @ ./browser/src/Plugins/PluginManager.ts
 @ ./browser/src/App.ts
 @ ./browser/src/index.tsx
 @ multi ./browser/src/index.tsx
```

And when running `npm link`:

```
An unhandled error occurred inside electron-rebuild
ENOENT: no such file or directory, open '/Users/redacted/Documents/projects/oni/node_modules/execa/node_modules/cross-spawn/package.json'

Error: ENOENT: no such file or directory, open '/Users/redacted/Documents/projects/oni/node_modules/execa/node_modules/cross-spawn/package.json'
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! oni@0.3.2 postinstall: `npm run install:plugins && electron-rebuild && opencollective postinstall`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the oni@0.3.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/redacted/.npm/_logs/2018-03-25T07_42_51_375Z-debug.log
```

I've attached the npm debug log:
[oni-link-debug.log](https://github.com/onivim/oni/files/1845102/oni-link-debug.log)

**Comment by parkerault** [comment]
I tried upgrading to node v9.9.0 and npm 5.8.0 and get this error on `npm link`:
```
error An unexpected error occurred: "/Users/redacted/Documents/projects/oni/node_modules/oniguruma: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /Users/redacted/Documents/projects/oni/node_modules/oniguruma
Output:
module.js:545
    throw err;
    ^

Error: Cannot find module '/Users/redacted/.nvm/versions/node/v9.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Function.Module.runMain (module.js:690:10)
```

**Comment by parkerault** [comment]
I was able to get it to build by downgrading to node v8.9.0 (LTS) and npm 5.6.0 and using the workaround in https://github.com/onivim/oni/issues/1460

**Comment by robin-pham** [comment]
Running into this on Arch Linux + node v8.11.1.

Similarily was able to get it to build following [this comment](https://github.com/onivim/oni/issues/1460#issuecomment-364875318). But the same error will still appear if I try to develop locally while running: `yarn start`/`npm run start`
```
[1] WARNING in ./node_modules/cross-spawn/index.js
[1] Module not found: Error: Can't resolve 'spawn-sync' in '/home/redacted/Documents/open_source/oni/node_modules/cross-spawn'
[1]  @ ./node_modules/cross-spawn/index.js 33:26-47
[1]  @ ./node_modules/shell-env/node_modules/execa/index.js
[1]  @ ./node_modules/shell-env/index.js
[1]  @ ./browser/src/Plugins/Api/Process.ts
[1]  @ ./browser/src/Plugins/PluginInstaller.ts
[1]  @ ./browser/src/Plugins/PluginManager.ts
[1]  @ ./browser/src/App.ts
[1]  @ ./browser/src/index.tsx
[1]  @ multi (webpack)-dev-server/client?http://localhost:8191 ./browser/src/index.tsx
```

Since it's just a warning, I'm still able to recompile and build stuff :man_shrugging:. 

Digging a bit deeper (https://github.com/moxystudio/node-cross-spawn/issues/87 and [the source code](https://github.com/moxystudio/node-cross-spawn/blob/5.1.0/index.js#L32)), requiring `spawn-sync` is only ever supposed to trigger if you're on an reallllly old version of Node where the inbuilt [child_process.spawnSync](https://nodejs.org/dist/latest-v8.x/docs/api/child_process.html#child_process_child_process_spawnsync_command_args_options) doesn't exist. Given that we're all encountering it on various versions of node, I think there's something much more whacky going on.

**Comment by dvisztempacct** [comment]
> I was able to get it to build by downgrading to node v8.10.0

This worked for me, too.
