### ISSUE TITLE
yarn install fails on bs-platform node module, slackware linux 14.2

### ISSUE THREAD

**Issue by hackedhead** [onivim/oni#2568]
**Oni Version:**
git clone commit 966fd2ccb1cd2c39f2a78adf812cf0b0785cf34d
**Neovim Version (Linux only):** v0.2.2
**Operating System:** Slackware Linux 14.2

**Issue:**
yarn install fails during building bs-platform node module

**Expected behavior:**
yarn install succeeds

**Actual behavior:**
error /home/hackedhead/oni/node_modules/bs-platform: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments: 
Directory: /home/hackedhead/oni/node_modules/bs-platform
Output:
ninja binary is copied from pre-distribution
No working prebuilt compiler
/bin/sh: ocamlc.opt: command not found
Build a local version of OCaml compiler, it may take a couple of minutes
configure again with local ocaml installed
The OCaml compiler, version 4.02.3+BS
Standard library directory: /home/hackedhead/oni/node_modules/bs-platform/vendor/ocaml/lib/ocaml

Use the compiler above
config finished
Making compiler
make -B -C lib -j 6 all
make[1]: Entering directory '/home/hackedhead/oni/node_modules/bs-platform/lib'
ocamlopt.opt -g -w -40-30 ../jscomp/stubs/ext_basic_hash_stubs.c whole_compiler.mli whole_compiler.ml  -o bsc.exe
ocamlopt.opt -g -w -40-30 ../jscomp/stubs/ext_basic_hash_stubs.c unix.cmxa str.cmxa bsb.mli bsb.ml -o bsb.exe
ocamlopt.opt -g -w -40-30 ../jscomp/stubs/ext_basic_hash_stubs.c bsppx.mli bsppx.ml -o bsppx.exe
ocamlopt.opt -g -w -40-30 ../jscomp/stubs/ext_basic_hash_stubs.c unix.cmxa -w -a bsb_helper.mli bsb_helper.ml -o bsb_helper.exe
ocamlopt.opt -w -40-30 -no-alias-deps -I +compiler-libs ocamlcommon.cmxa refmt_main.mli refmt_main.ml -o refmt.exe
ocamlopt.opt -w -40-30 -no-alias-deps -I +compiler-libs ocamlcommon.cmxa refmt_main3.mli refmt_main3.ml -o refmt3.exe
ocamlopt.opt -w -40-30 -no-alias-deps -I +compiler-libs ocamlcommon.cmxa reactjs_jsx_ppx_v2.mli reactjs_jsx_ppx_v2.ml -o reactjs_jsx_ppx_2.exe
Makefile:33: recipe for target 'bsc.exe' failed
make[1]: *** [bsc.exe] Segmentation fault
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/hackedhead/oni/node_modules/bs-platform/lib'
Makefile:9: recipe for target 'world' failed
make: *** [world] Error 2
child_process.js:644
    throw err;
    ^

Error: Command failed: make world && make install
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at non_windows_npm_release (/home/hackedhead/oni/node_modules/bs-platform/scripts/install.js:155:23)
    at Object.<anonymous> (/home/hackedhead/oni/node_modules/bs-platform/scripts/install.js:177:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Steps to reproduce:**
`git clone`
`git checkout 966fd2ccb1cd2c39f2a78adf812cf0b0785cf34d`
`cd oni`
`yarn install`

**Comment by badosu** [comment]
Can you provide your node and glibc version?
