### ISSUE TITLE
Can't launch offline (possibly an electron bug)

### ISSUE THREAD

**Issue by sullyj3** [onivim/oni#2641]
**Oni Version:** 0.3.6
**Neovim Version (Linux only):**
**Operating System:** Windows 10

**Issue:**
When offline:

```
C:\Users\James>oni
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13
```
And the window fails to open.

I think it's electron/electron/issues/14117, the error message is the same. The issue seems to have been closed mistakenly.

**Comment by CrossR** [comment]
Looks like that issue points to https://github.com/electron/electron/issues/6437 so we should keep an eye on that.

**Comment by sullyj3** [comment]
It seems like some people are no longer getting the issue using electron 3, how labor intensive would it be to update? Would it be doable for someone with a little programming experience, but not much javascript/typescript/experience with electron?
