### ISSUE TITLE
Add ruby language server support

### ISSUE THREAD

**Issue by badosu** [onivim/oni#901]
Currently the available LS for Ruby is present at (https://github.com/mtsmfm/language_server-ruby), however it is on Alpha stage at the moment.

I tried not to add this earlier, but the prospect of a deeper integration with Oni excites me.

This issue can be maintained to keep track of this until it is deemed good enough to be addressed.

**Comment by keforbes** [comment]
Could you try following the steps in the wiki to configure the LSP yourself?  I'm curious if it'll work.
https://github.com/onivim/oni/wiki/Language-Support#configuration

**Comment by bryphe** [comment]
Yes, this would be a great test case of the new language configuration model 😄 It seems like a relatively straightforward one to configure.

Let me know if you hit any issues or need any clarifications

**Comment by imustafin** [comment]
I tried to configure the LS myself by adding
```
"language.ruby.languageServer.command": "language_server-ruby",
```
to the config file.

When I open a ruby file I get this in Oni console:

```
[LanguageClientProcess] Ending language server session
[LanguageClientProcess]: Starting process via 'language_server-ruby'
[LanguageClientProcess]: Started process 29198
[LANGUAGE CLIENT - STDERR]: /home/ilgiz/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0/lib/bundler.rb:23:in `replace': Invalid argument - setenv() (Errno::EINVAL)
	from /home/ilgiz/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0/lib/bundler.rb:23:in `<module:Bundler>'
	from /home/ilgiz/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0/lib/bundler.rb:20:in `<top (required)>'
	from /home/ilgiz/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /home/ilgiz/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /home/ilgiz/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/ilgiz/.rvm/gems/ruby-2.4.1@global/gems/bundler-unload-1.0.2/lib/bundler-unload.rb:1:in `<top (required)>'
	from /home/ilgiz/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ilgiz/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ilgiz/.rvm/gems/ruby-2.4.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:82:in `setup'
	from /home/ilgiz/.rvm/gems/ruby-2.4.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:124:in `check'
	from /home/ilgiz/.rvm/gems/ruby-2.4.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:131:in `<top (required)>'
	from /home/ilgiz/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /home/ilgiz/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /home/ilgiz/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/ilgiz/.rvm/gems/ruby-2.4.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	from /home/ilgiz/.rvm/gems/ruby-2.4.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:50:in `block in run'
	from /home/ilgiz/.rvm/gems/ruby-2.4.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:49:in `each'
	from /home/ilgiz/.rvm/gems/ruby-2.4.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:49:in `run'
	from /home/ilgiz/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:10:in `<main>'
```

As you can see I am using ruby-2.4.1 with RVM on Arch Linux.

Running `language_server-ruby` works.

**Comment by badosu** [comment]
Thanks @imustafin!

Make sure to install the gem with your system or your current workspace's ruby, I did that with `chruby` and `gem install language-server_ruby`.

Although it initializes and it seems like it sends and receives message from the LSP I noticed no features in the editing experience:

```
[LANGUAGE CLIENT - STDERR]: D, [2018-04-23T18:46:52.975004 #15918] DEBUG -- : Receive: {
  "jsonrpc": "2.0",
  "id": 0,
  "method": "initialize",
  "params": {
    "clientName": "oni",
    "rootPath": "/home/badosu/Code/mymoc/spec/models",
    "rootUri": "file:///home/badosu/Code/mymoc/spec/models",
    "capabilities": {
      "workspace": {
        "applyEdit": true,
        "workspaceEdit": {
          "documentChanges": false
        },
        "didChangeConfiguration": {
          "dynamicRegistration": false
        },
        "didChangeWatchedFiles": {
          "dynamicRegistration": false
        },
        "symbol": {
          "dynamicRegistration": false
        },
        "executeCommand": {
          "dynamicRegistration": false
        }
      },
      "textDocument": {
        "synchronization": {
          "dynamicRegistration": false,
          "willSave": false,
          "willSaveWaitUntil": false,
          "didSave": true
        },
        "completion": {
          "dynamicRegistration": false,
          "completionItem": {
            "snippetSupport": true,
            "commitCharactersSupport": true,
            "documentationFormat": [
              "plaintext"
            ]
          },
          "completionItemKind": {
          },
          "contextSupport": false
        },
        "hover": {
          "dynamicRegistration": false,
          "contentFormat": [
            "plaintext"
          ]
        },
        "signatureHelp": {
          "dynamicRegistration": false,
          "signatureInformation": {
            "documentationFormat": [
              "plaintext"
            ]
          }
        },
        "references": {
          "dynamicRegistration": false
        },
        "documentSymbol": {
          "dynamicRegistration": false
        },
        "formatting": {
          "dynamicRegistration": false
        },
        "rangeFormatting": {
          "dynamicRegistration": false
        },
        "definition": {
          "dynamicRegistration": false
        },
        "codeAction": {
          "dynamicRegistration": false
        },
        "codeLens": {
          "dynamicRegistration": false
        },
        "rename": {
          "dynamicRegistration": false
        }
      }
    }
  }
}

/opt/oni/resources/app/lib/browser/bundle.js:1 [LANGUAGE CLIENT - STDERR]: D, [2018-04-23T18:46:52.975096 #15918] DEBUG -- : Respond: id: 0, result: {
  "capabilities": {
    "textDocumentSync": {
      "change": 1
    },
    "completionProvider": {
      "resolveProvider": true,
      "triggerCharacters": [
        "."
      ]
    }
  }
}
```

When a new ruby file is opened synchronization fails and the LSP icon is replaced by the rotating spinner. No further communication between server and client is sent anymore.

**Comment by badosu** [comment]
[Solargraph](https://github.com/castwide/solargraph) works, see the [updated wiki](https://github.com/onivim/oni/wiki/Language-Support#ruby) for setup instructions
