### ISSUE TITLE
Filetype wheel continuously spinning

### ISSUE THREAD

**Issue by bpierce1** [onivim/oni#961]
I'm seeing a filetype wheel that continuously spins on any file type. Here's an example:

![image](https://user-images.githubusercontent.com/2482596/32906299-5a880792-cab1-11e7-9898-982639b69dcd.png)

It's happening at least on Ubuntu 14.04 and OS X with the latest version 0.2.17 (and some previous versions as well). 

I notice the CPU usage is also much higher while this is happening. Have I misconfigured something?

**Comment by bryphe** [comment]
Thanks for logging the issue, @bpierce1 !

I believe there are two problems here:
- `javascript.jsx` not supported - we should be bringing in the out-of-box javascript language service (#882)
- In general, if the filetype is not recognized / no language server shown, we are showing that spinner (even in places like the quickfix list).

**Comment by bpierce1** [comment]
Yes that was an example, but I see it on all filetypes. But you're right - I currently don't have a language server. Is there a way to disable the need for the language server so that the CPU utilization isn't so high?

By the way, I noticed the spinning began in 0.2.15, and isn't there in 0.2.14.

**Comment by Metamist** [comment]
In my developer tools, I am getting this error:
```
Error: No content available.
    at TypeScriptServerHost._parseResponse (/home/metamist/apps/oni/resources/app/vim/core/oni-plugin-typescript/lib/TypeScriptServerHost.js:239:49)
    at Interface.<anonymous> (/home/metamist/apps/oni/resources/app/vim/core/oni-plugin-typescript/lib/TypeScriptServerHost.js:60:23)
    at emitOne (events.js:115:13)
    at Interface.emit (events.js:210:7)
    at Interface._onLine (readline.js:278:10)
    at Interface._normalWrite (readline.js:420:12)
    at Socket.ondata (readline.js:138:10)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
```
Is it trying to use typescript inside `javascript.jsx` files?

**Comment by CrossR** [comment]
I used to notice this, but in the latest release, it looks like its been fixed.
Can this be closed now?

**Comment by bryphe** [comment]
Cool, ya, it should be fixed now (at least the latest release had some improvements around the statusbar state). Thanks @CrossR !
